<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    protected $countries = [
        ['name' => 'Afghanistan', 'abbreviation' => 'AFG', 'currency' => 'Afghan Afghani (AFN)'],
        ['name' => 'Albania', 'abbreviation' => 'ALB', 'currency' => 'Albanian Lek (ALL)'],
        ['name' => 'Algeria', 'abbreviation' => 'DZA', 'currency' => 'Algerian Dinar (DZD)'],
        ['name' => 'Andorra', 'abbreviation' => 'AND', 'currency' => 'Euro (EUR)'],
        ['name' => 'Angola', 'abbreviation' => 'AGO', 'currency' => 'Angolan Kwanza (AOA)'],
        ['name' => 'Antigua and Barbuda', 'abbreviation' => 'ATG', 'currency' => 'Eastern Caribbean Dollar (XCD)'],
        ['name' => 'Argentina', 'abbreviation' => 'ARG', 'currency' => 'Argentine Peso (ARS)'],
        ['name' => 'Armenia', 'abbreviation' => 'ARM', 'currency' => 'Armenian Dram (AMD)'],
        ['name' => 'Australia', 'abbreviation' => 'AUS', 'currency' => 'Australian Dollar (AUD)'],
        ['name' => 'Austria', 'abbreviation' => 'AUT', 'currency' => 'Euro (EUR)'],
        ['name' => 'Azerbaijan', 'abbreviation' => 'AZE', 'currency' => 'Azerbaijani Manat (AZN)'],
        ['name' => 'Bahamas', 'abbreviation' => 'BHS', 'currency' => 'Bahamian Dollar (BSD)'],
        ['name' => 'Bahrain', 'abbreviation' => 'BHR', 'currency' => 'Bahraini Dinar (BHD)'],
        ['name' => 'Bangladesh', 'abbreviation' => 'BGD', 'currency' => 'Bangladeshi Taka (BDT)'],
        ['name' => 'Barbados', 'abbreviation' => 'BRB', 'currency' => 'Barbadian Dollar (BBD)'],
        ['name' => 'Belarus', 'abbreviation' => 'BLR', 'currency' => 'Belarusian Ruble (BYN)'],
        ['name' => 'Belgium', 'abbreviation' => 'BEL', 'currency' => 'Euro (EUR)'],
        ['name' => 'Belize', 'abbreviation' => 'BLZ', 'currency' => 'Belize Dollar (BZD)'],
        ['name' => 'Benin', 'abbreviation' => 'BEN', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Bhutan', 'abbreviation' => 'BTN', 'currency' => 'Bhutanese Ngultrum (BTN)'],
        ['name' => 'Bolivia', 'abbreviation' => 'BOL', 'currency' => 'Bolivian Boliviano (BOB)'],
        ['name' => 'Bosnia and Herzegovina', 'abbreviation' => 'BIH', 'currency' => 'Bosnia and Herzegovina Convertible Mark (BAM)'],
        ['name' => 'Botswana', 'abbreviation' => 'BWA', 'currency' => 'Botswana Pula (BWP)'],
        ['name' => 'Brazil', 'abbreviation' => 'BRA', 'currency' => 'Brazilian Real (BRL)'],
        ['name' => 'Brunei', 'abbreviation' => 'BRN', 'currency' => 'Brunei Dollar (BND)'],
        ['name' => 'Bulgaria', 'abbreviation' => 'BGR', 'currency' => 'Bulgarian Lev (BGN)'],
        ['name' => 'Burkina Faso', 'abbreviation' => 'BFA', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Burundi', 'abbreviation' => 'BDI', 'currency' => 'Burundian Franc (BIF)'],
        ['name' => 'Cabo Verde', 'abbreviation' => 'CPV', 'currency' => 'Cape Verdean Escudo (CVE)'],
        ['name' => 'Cambodia', 'abbreviation' => 'KHM', 'currency' => 'Cambodian Riel (KHR)'],
        ['name' => 'Cameroon', 'abbreviation' => 'CMR', 'currency' => 'Central African CFA franc (XAF)'],
        ['name' => 'Canada', 'abbreviation' => 'CAN', 'currency' => 'Canadian Dollar (CAD)'],
        ['name' => 'Central African Republic', 'abbreviation' => 'CAF', 'currency' => 'Central African CFA franc (XAF)'],
        ['name' => 'Chad', 'abbreviation' => 'TCD', 'currency' => 'Central African CFA franc (XAF)'],
        ['name' => 'Chile', 'abbreviation' => 'CHL', 'currency' => 'Chilean Peso (CLP)'],
        ['name' => 'China', 'abbreviation' => 'CHN', 'currency' => 'Chinese Yuan (CNY)'],
        ['name' => 'Colombia', 'abbreviation' => 'COL', 'currency' => 'Colombian Peso (COP)'],
        ['name' => 'Comoros', 'abbreviation' => 'COM', 'currency' => 'Comorian Franc (KMF)'],
        ['name' => 'Congo (Congo-Brazzaville)', 'abbreviation' => 'COG', 'currency' => 'Central African CFA franc (XAF)'],
        ['name' => 'Costa Rica', 'abbreviation' => 'CRI', 'currency' => 'Costa Rican Colón (CRC)'],
        ['name' => 'Croatia', 'abbreviation' => 'HRV', 'currency' => 'Croatian Kuna (HRK)'],
        ['name' => 'Cuba', 'abbreviation' => 'CUB', 'currency' => 'Cuban Peso (CUP)'],
        ['name' => 'Cyprus', 'abbreviation' => 'CYP', 'currency' => 'Euro (EUR)'],
        ['name' => 'Czechia (Czech Republic)', 'abbreviation' => 'CZE', 'currency' => 'Czech Koruna (CZK)'],
        ['name' => 'Democratic Republic of the Congo', 'abbreviation' => 'COD', 'currency' => 'Congolese Franc (CDF)'],
        ['name' => 'Denmark', 'abbreviation' => 'DNK', 'currency' => 'Danish Krone (DKK)'],
        ['name' => 'Djibouti', 'abbreviation' => 'DJI', 'currency' => 'Djiboutian Franc (DJF)'],
        ['name' => 'Dominica', 'abbreviation' => 'DMA', 'currency' => 'East Caribbean Dollar (XCD)'],
        ['name' => 'Dominican Republic', 'abbreviation' => 'DOM', 'currency' => 'Dominican Peso (DOP)'],
        ['name' => 'East Timor (Timor-Leste)', 'abbreviation' => 'TLS', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Ecuador', 'abbreviation' => 'ECU', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Egypt', 'abbreviation' => 'EGY', 'currency' => 'Egyptian Pound (EGP)'],
        ['name' => 'El Salvador', 'abbreviation' => 'SLV', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Equatorial Guinea', 'abbreviation' => 'GNQ', 'currency' => 'Central African CFA franc (XAF)'],
        ['name' => 'Eritrea', 'abbreviation' => 'ERI', 'currency' => 'Eritrean Nakfa (ERN)'],
        ['name' => 'Estonia', 'abbreviation' => 'EST', 'currency' => 'Euro (EUR)'],
        ['name' => 'Eswatini (fmr. "Swaziland")', 'abbreviation' => 'SWZ', 'currency' => 'Swazi Lilangeni (SZL)'],
        ['name' => 'Ethiopia', 'abbreviation' => 'ETH', 'currency' => 'Ethiopian Birr (ETB)'],
        ['name' => 'Fiji', 'abbreviation' => 'FJI', 'currency' => 'Fijian Dollar (FJD)'],
        ['name' => 'Finland', 'abbreviation' => 'FIN', 'currency' => 'Euro (EUR)'],
        ['name' => 'France', 'abbreviation' => 'FRA', 'currency' => 'Euro (EUR)'],
        ['name' => 'Gabon', 'abbreviation' => 'GAB', 'currency' => 'Central African CFA franc (XAF)'],
        ['name' => 'Gambia', 'abbreviation' => 'GMB', 'currency' => 'Gambian Dalasi (GMD)'],
        ['name' => 'Georgia', 'abbreviation' => 'GEO', 'currency' => 'Georgian Lari (GEL)'],
        ['name' => 'Germany', 'abbreviation' => 'DEU', 'currency' => 'Euro (EUR)'],
        ['name' => 'Ghana', 'abbreviation' => 'GHA', 'currency' => 'Ghanaian Cedi (GHS)'],
        ['name' => 'Greece', 'abbreviation' => 'GRC', 'currency' => 'Euro (EUR)'],
        ['name' => 'Grenada', 'abbreviation' => 'GRD', 'currency' => 'East Caribbean Dollar (XCD)'],
        ['name' => 'Guatemala', 'abbreviation' => 'GTM', 'currency' => 'Guatemalan Quetzal (GTQ)'],
        ['name' => 'Guinea', 'abbreviation' => 'GIN', 'currency' => 'Guinean Franc (GNF)'],
        ['name' => 'Guinea-Bissau', 'abbreviation' => 'GNB', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Guyana', 'abbreviation' => 'GUY', 'currency' => 'Guyanese Dollar (GYD)'],
        ['name' => 'Haiti', 'abbreviation' => 'HTI', 'currency' => 'Haitian Gourde (HTG)'],
        ['name' => 'Holy See', 'abbreviation' => 'VAT', 'currency' => 'Euro (EUR)'],
        ['name' => 'Honduras', 'abbreviation' => 'HND', 'currency' => 'Honduran Lempira (HNL)'],
        ['name' => 'Hungary', 'abbreviation' => 'HUN', 'currency' => 'Hungarian Forint (HUF)'],
        ['name' => 'Iceland', 'abbreviation' => 'ISL', 'currency' => 'Icelandic Króna (ISK)'],
        ['name' => 'India', 'abbreviation' => 'IND', 'currency' => 'Indian Rupee (INR)'],
        ['name' => 'Indonesia', 'abbreviation' => 'IDN', 'currency' => 'Indonesian Rupiah (IDR)'],
        ['name' => 'Iran', 'abbreviation' => 'IRN', 'currency' => 'Iranian Rial (IRR)'],
        ['name' => 'Iraq', 'abbreviation' => 'IRQ', 'currency' => 'Iraqi Dinar (IQD)'],
        ['name' => 'Ireland', 'abbreviation' => 'IRL', 'currency' => 'Euro (EUR)'],
        ['name' => 'Israel', 'abbreviation' => 'ISR', 'currency' => 'Israeli New Shekel (ILS)'],
        ['name' => 'Italy', 'abbreviation' => 'ITA', 'currency' => 'Euro (EUR)'],
        ['name' => 'Jamaica', 'abbreviation' => 'JAM', 'currency' => 'Jamaican Dollar (JMD)'],
        ['name' => 'Japan', 'abbreviation' => 'JPN', 'currency' => 'Japanese Yen (JPY)'],
        ['name' => 'Jordan', 'abbreviation' => 'JOR', 'currency' => 'Jordanian Dinar (JOD)'],
        ['name' => 'Kazakhstan', 'abbreviation' => 'KAZ', 'currency' => 'Kazakhstani Tenge (KZT)'],
        ['name' => 'Kenya', 'abbreviation' => 'KEN', 'currency' => 'Kenyan Shilling (KES)'],
        ['name' => 'Kiribati', 'abbreviation' => 'KIR', 'currency' => 'Australian Dollar (AUD)'],
        ['name' => 'Kuwait', 'abbreviation' => 'KWT', 'currency' => 'Kuwaiti Dinar (KWD)'],
        ['name' => 'Kyrgyzstan', 'abbreviation' => 'KGZ', 'currency' => 'Kyrgyzstani Som (KGS)'],
        ['name' => 'Laos', 'abbreviation' => 'LAO', 'currency' => 'Lao Kip (LAK)'],
        ['name' => 'Latvia', 'abbreviation' => 'LVA', 'currency' => 'Euro (EUR)'],
        ['name' => 'Lebanon', 'abbreviation' => 'LBN', 'currency' => 'Lebanese Pound (LBP)'],
        ['name' => 'Lesotho', 'abbreviation' => 'LSO', 'currency' => 'Lesotho Loti (LSL)'],
        ['name' => 'Liberia', 'abbreviation' => 'LBR', 'currency' => 'Liberian Dollar (LRD)'],
        ['name' => 'Libya', 'abbreviation' => 'LBY', 'currency' => 'Libyan Dinar (LYD)'],
        ['name' => 'Liechtenstein', 'abbreviation' => 'LIE', 'currency' => 'Swiss Franc (CHF)'],
        ['name' => 'Lithuania', 'abbreviation' => 'LTU', 'currency' => 'Euro (EUR)'],
        ['name' => 'Luxembourg', 'abbreviation' => 'LU', 'currency' => 'Euro (EUR)'],
        ['name' => 'Madagascar', 'abbreviation' => 'MG', 'currency' => 'Malagasy Ariary (MGA)'],
        ['name' => 'Malawi', 'abbreviation' => 'MW', 'currency' => 'Malawian Kwacha (MWK)'],
        ['name' => 'Malaysia', 'abbreviation' => 'MY', 'currency' => 'Malaysian Ringgit (MYR)'],
        ['name' => 'Maldives', 'abbreviation' => 'MV', 'currency' => 'Maldivian Rufiyaa (MVR)'],
        ['name' => 'Mali', 'abbreviation' => 'ML', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Malta', 'abbreviation' => 'MT', 'currency' => 'Euro (EUR)'],
        ['name' => 'Marshall Islands', 'abbreviation' => 'MH', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Mauritania', 'abbreviation' => 'MR', 'currency' => 'Mauritanian Ouguiya (MRU)'],
        ['name' => 'Mauritius', 'abbreviation' => 'MU', 'currency' => 'Mauritian Rupee (MUR)'],
        ['name' => 'Mexico', 'abbreviation' => 'MX', 'currency' => 'Mexican Peso (MXN)'],
        ['name' => 'Micronesia', 'abbreviation' => 'FM', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Moldova', 'abbreviation' => 'MD', 'currency' => 'Moldovan Leu (MDL)'],
        ['name' => 'Monaco', 'abbreviation' => 'MC', 'currency' => 'Euro (EUR)'],
        ['name' => 'Mongolia', 'abbreviation' => 'MN', 'currency' => 'Mongolian Tugrik (MNT)'],
        ['name' => 'Montenegro', 'abbreviation' => 'ME', 'currency' => 'Euro (EUR)'],
        ['name' => 'Morocco', 'abbreviation' => 'MA', 'currency' => 'Moroccan Dirham (MAD)'],
        ['name' => 'Mozambique', 'abbreviation' => 'MZ', 'currency' => 'Mozambican Metical (MZN)'],
        ['name' => 'Myanmar', 'abbreviation' => 'MM', 'currency' => 'Myanmar Kyat (MMK)'],
        ['name' => 'Namibia', 'abbreviation' => 'NA', 'currency' => 'Namibian Dollar (NAD)'],
        ['name' => 'Nauru', 'abbreviation' => 'NR', 'currency' => 'Australian Dollar (AUD)'],
        ['name' => 'Nepal', 'abbreviation' => 'NP', 'currency' => 'Nepalese Rupee (NPR)'],
        ['name' => 'Netherlands', 'abbreviation' => 'NL', 'currency' => 'Euro (EUR)'],
        ['name' => 'New Zealand', 'abbreviation' => 'NZ', 'currency' => 'New Zealand Dollar (NZD)'],
        ['name' => 'Nicaragua', 'abbreviation' => 'NI', 'currency' => 'Nicaraguan Córdoba (NIO)'],
        ['name' => 'Niger', 'abbreviation' => 'NE', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Nigeria', 'abbreviation' => 'NG', 'currency' => 'Nigerian Naira (NGN)'],
        ['name' => 'North Korea', 'abbreviation' => 'KP', 'currency' => 'North Korean Won (KPW)'],
        ['name' => 'North Macedonia', 'abbreviation' => 'MK', 'currency' => 'Macedonian Denar (MKD)'],
        ['name' => 'Norway', 'abbreviation' => 'NO', 'currency' => 'Norwegian Krone (NOK)'],
        ['name' => 'Oman', 'abbreviation' => 'OM', 'currency' => 'Omani Rial (OMR)'],
        ['name' => 'Pakistan', 'abbreviation' => 'PK', 'currency' => 'Pakistani Rupee (PKR)'],
        ['name' => 'Palau', 'abbreviation' => 'PW', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Panama', 'abbreviation' => 'PA', 'currency' => 'Panamanian Balboa (PAB)'],
        ['name' => 'Papua New Guinea', 'abbreviation' => 'PG', 'currency' => 'Papua New Guinean Kina (PGK)'],
        ['name' => 'Paraguay', 'abbreviation' => 'PY', 'currency' => 'Paraguayan Guarani (PYG)'],
        ['name' => 'Peru', 'abbreviation' => 'PE', 'currency' => 'Peruvian Nuevo Sol (PEN)'],
        ['name' => 'Philippines', 'abbreviation' => 'PH', 'currency' => 'Philippine Peso (PHP)'],
        ['name' => 'Poland', 'abbreviation' => 'PL', 'currency' => 'Polish Złoty (PLN)'],
        ['name' => 'Portugal', 'abbreviation' => 'PT', 'currency' => 'Euro (EUR)'],
        ['name' => 'Qatar', 'abbreviation' => 'QA', 'currency' => 'Qatari Riyal (QAR)'],
        ['name' => 'Romania', 'abbreviation' => 'RO', 'currency' => 'Romanian Leu (RON)'],
        ['name' => 'Russia', 'abbreviation' => 'RU', 'currency' => 'Russian Ruble (RUB)'],
        ['name' => 'Rwanda', 'abbreviation' => 'RW', 'currency' => 'Rwandan Franc (RWF)'],
        ['name' => 'Saint Kitts and Nevis', 'abbreviation' => 'KN', 'currency' => 'Eastern Caribbean Dollar (XCD)'],
        ['name' => 'Saint Lucia', 'abbreviation' => 'LC', 'currency' => 'Eastern Caribbean Dollar (XCD)'],
        ['name' => 'Saint Vincent and the Grenadines', 'abbreviation' => 'VC', 'currency' => 'Eastern Caribbean Dollar (XCD)'],
        ['name' => 'Samoa', 'abbreviation' => 'WS', 'currency' => 'Samoan Tala (WST)'],
        ['name' => 'San Marino', 'abbreviation' => 'SM', 'currency' => 'Euro (EUR)'],
        ['name' => 'Sao Tome and Principe', 'abbreviation' => 'ST', 'currency' => 'São Tomé and Príncipe Dobra (STN)'],
        ['name' => 'Saudi Arabia', 'abbreviation' => 'SA', 'currency' => 'Saudi Riyal (SAR)'],
        ['name' => 'Senegal', 'abbreviation' => 'SN', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Serbia', 'abbreviation' => 'RS', 'currency' => 'Serbian Dinar (RSD)'],
        ['name' => 'Seychelles', 'abbreviation' => 'SC', 'currency' => 'Seychellois Rupee (SCR)'],
        ['name' => 'Sierra Leone', 'abbreviation' => 'SL', 'currency' => 'Sierra Leonean Leone (SLL)'],
        ['name' => 'Singapore', 'abbreviation' => 'SG', 'currency' => 'Singapore Dollar (SGD)'],
        ['name' => 'Slovakia', 'abbreviation' => 'SK', 'currency' => 'Euro (EUR)'],
        ['name' => 'Slovenia', 'abbreviation' => 'SI', 'currency' => 'Euro (EUR)'],
        ['name' => 'Solomon Islands', 'abbreviation' => 'SB', 'currency' => 'Solomon Islands Dollar (SBD)'],
        ['name' => 'Somalia', 'abbreviation' => 'SO', 'currency' => 'Somali Shilling (SOS)'],
        ['name' => 'South Africa', 'abbreviation' => 'ZA', 'currency' => 'South African Rand (ZAR)'],
        ['name' => 'South Korea', 'abbreviation' => 'KR', 'currency' => 'South Korean Won (KRW)'],
        ['name' => 'South Sudan', 'abbreviation' => 'SS', 'currency' => 'South Sudanese Pound (SSP)'],
        ['name' => 'Spain', 'abbreviation' => 'ES', 'currency' => 'Euro (EUR)'],
        ['name' => 'Sri Lanka', 'abbreviation' => 'LK', 'currency' => 'Sri Lankan Rupee (LKR)'],
        ['name' => 'Sudan', 'abbreviation' => 'SD', 'currency' => 'Sudanese Pound (SDG)'],
        ['name' => 'Suriname', 'abbreviation' => 'SR', 'currency' => 'Surinamese Dollar (SRD)'],
        ['name' => 'Sweden', 'abbreviation' => 'SE', 'currency' => 'Swedish Krona (SEK)'],
        ['name' => 'Switzerland', 'abbreviation' => 'CH', 'currency' => 'Swiss Franc (CHF)'],
        ['name' => 'Syria', 'abbreviation' => 'SY', 'currency' => 'Syrian Pound (SYP)'],
        ['name' => 'Tajikistan', 'abbreviation' => 'TJ', 'currency' => 'Tajikistani Somoni (TJS)'],
        ['name' => 'Tanzania', 'abbreviation' => 'TZ', 'currency' => 'Tanzanian Shilling (TZS)'],
        ['name' => 'Thailand', 'abbreviation' => 'TH', 'currency' => 'Thai Baht (THB)'],
        ['name' => 'Timor-Leste', 'abbreviation' => 'TL', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Togo', 'abbreviation' => 'TG', 'currency' => 'West African CFA franc (XOF)'],
        ['name' => 'Tonga', 'abbreviation' => 'TO', 'currency' => 'Tongan Paʻanga (TOP)'],
        ['name' => 'Trinidad and Tobago', 'abbreviation' => 'TT', 'currency' => 'Trinidad and Tobago Dollar (TTD)'],
        ['name' => 'Tunisia', 'abbreviation' => 'TN', 'currency' => 'Tunisian Dinar (TND)'],
        ['name' => 'Turkey', 'abbreviation' => 'TR', 'currency' => 'Turkish Lira (TRY)'],
        ['name' => 'Turkmenistan', 'abbreviation' => 'TM', 'currency' => 'Turkmenistan Manat (TMT)'],
        ['name' => 'Tuvalu', 'abbreviation' => 'TV', 'currency' => 'Australian Dollar (AUD)'],
        ['name' => 'Uganda', 'abbreviation' => 'UG', 'currency' => 'Ugandan Shilling (UGX)'],
        ['name' => 'Ukraine', 'abbreviation' => 'UA', 'currency' => 'Ukrainian Hryvnia (UAH)'],
        ['name' => 'United Arab Emirates', 'abbreviation' => 'AE', 'currency' => 'United Arab Emirates Dirham (AED)'],
        ['name' => 'United Kingdom', 'abbreviation' => 'GB', 'currency' => 'British Pound (GBP)'],
        ['name' => 'United States', 'abbreviation' => 'US', 'currency' => 'United States Dollar (USD)'],
        ['name' => 'Uruguay', 'abbreviation' => 'UY', 'currency' => 'Uruguayan Peso (UYU)'],
        ['name' => 'Uzbekistan', 'abbreviation' => 'UZ', 'currency' => 'Uzbekistani Som (UZS)'],
        ['name' => 'Vanuatu', 'abbreviation' => 'VU', 'currency' => 'Vanuatu Vatu (VUV)'],
        ['name' => 'Vatican City', 'abbreviation' => 'VA', 'currency' => 'Euro (EUR)'],
        ['name' => 'Venezuela', 'abbreviation' => 'VE', 'currency' => 'Venezuelan Bolívar (VES)'],
        ['name' => 'Vietnam', 'abbreviation' => 'VN', 'currency' => 'Vietnamese Dong (VND)'],
        ['name' => 'Yemen', 'abbreviation' => 'YE', 'currency' => 'Yemeni Rial (YER)'],
        ['name' => 'Zambia', 'abbreviation' => 'ZM', 'currency' => 'Zambian Kwacha (ZMW)'],
        ['name' => 'Zimbabwe', 'abbreviation' => 'ZW', 'currency' => 'Zimbabwean Dollar (ZWL)'],
    ];
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->countries as $country) {
            DB::table('countries')->insert([
                'name' => $country['name'],
                'abbreviation' => $country['abbreviation'],
                'currency' => $country['currency'],
            ]);
        }
    }
}
